I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2596, in script
    python:
  File "game/script.rpy", line 2606, in <module>
    act3Time = act3_time_string
NameError: name 'act3_time_string' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2596, in script
    python:
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 2606, in <module>
    act3Time = act3_time_string
NameError: name 'act3_time_string' is not defined

Darwin-21.1.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
IDP2022 1.0
Thu Jun  2 23:40:55 2022
