I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 966, in script
    call screen piano()
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "renpy/common/00action_other.rpy", line 537, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/script.rpy", line 1747, in checkpiano
    renpy.say([name],"that wasn't right.. let me try again.", interact = False)
TypeError: 'RevertableList' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 966, in script
    call screen piano()
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 2015, in execute
    self.call("execute")
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 2003, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/exports.py", line 3136, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/core.py", line 4160, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/layout.py", line 1102, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/transition.py", line 48, in event
    return self.new_widget.event(ev, x, y, st) # E1101
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/layout.py", line 1102, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/layout.py", line 1102, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/screen.py", line 727, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/layout.py", line 1102, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/behavior.py", line 983, in event
    return handle_click(self.clicked)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/behavior.py", line 918, in handle_click
    rv = run(action)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/behavior.py", line 323, in run
    new_rv = run(i, *args, **kwargs)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/behavior.py", line 330, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_other.rpy", line 537, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/script.rpy", line 1747, in checkpiano
    renpy.say([name],"that wasn't right.. let me try again.", interact = False)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
TypeError: 'RevertableList' object is not callable

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
IDP2022 1.0
Fri May 27 13:59:54 2022
