I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/example.rpy", line 113, in script
Exception: Not a displayable: <store._m1_example__Example object at 0x10607dbd0>

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/trooper6/Desktop Folders/Programming/RenPy/renpy-6.99.0-sdk/renpy/bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "/Users/trooper6/Desktop Folders/Programming/RenPy/renpy-6.99.0-sdk/renpy/main.py", line 419, in main
    game.context().run(node)
  File "game/example.rpy", line 113, in script
  File "/Users/trooper6/Desktop Folders/Programming/RenPy/renpy-6.99.0-sdk/renpy/ast.py", line 911, in execute
    renpy.exports.image(self.imgname, img)
  File "/Users/trooper6/Desktop Folders/Programming/RenPy/renpy-6.99.0-sdk/renpy/exports.py", line 347, in image
    d = renpy.easy.displayable(d)
  File "/Users/trooper6/Desktop Folders/Programming/RenPy/renpy-6.99.0-sdk/renpy/easy.py", line 108, in displayable
    raise Exception("Not a displayable: %r" % (d,))
Exception: Not a displayable: <store._m1_example__Example object at 0x10607dbd0>

Darwin-16.6.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
Renpy Imagebuttons GUI Sample 1.0
